import type { Metadata } from "next";
import { Inter, Noto_Serif } from "next/font/google";
import "../styles/globals.css";
import Menu from "@/components/header";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});
const noto = Noto_Serif({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-noto-serif",
});

export const metadata: Metadata = {
  title: "jojo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${noto.variable} font-serif`}>
        {children}
      </body>
    </html>
  );
}
